logging:
  level:
    org.sprinframework: DEBUG

spring:
  jpa:
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:bugtracker
  h2:
    console:
      enabled: true
      path: /h2-console